import { formatLongDate, type OfferLetterCandidateFilled } from "./types.js";

const OFFICE_ADDRESS = `Par Marketing Pvt. Ltd.
Plot No. 1, Shah Industries,
Near Ghanshyam Industrial Estate,
Veera Desai Road, Andheri West,
Mumbai - 400053, Maharashtra.`;

export function offerLetterPlainParagraphs(c: OfferLetterCandidateFilled): string[] {
  const designation = c.position;
  const joinDate = formatLongDate(c.dateOfJoining);
  const acceptBy = formatLongDate(c.acceptByDate);
  const validUntil = formatLongDate(c.offerValidUntil);

  return [
    `Dear ${c.salutation} ${c.name},`,
    "",
    `We are pleased to offer you employment with ${c.companyName} (“the Company”) for the position of ${designation}.`,
    "",
    "Following our discussions and the selection process, we believe that your qualifications, experience and capabilities are well suited to the requirements of the role. We look forward to you becoming a valued member of our organisation and contributing to the continued growth and success of the Company.",
    "",
    "Your proposed employment details are as follows:",
    "",
    `Designation: ${designation}`,
    `Department: ${c.department}`,
    `Date of Joining: ${joinDate}`,
    `Place of Posting: ${c.placeOfPosting}`,
    `Reporting To: ${c.reportingTo}`,
    `Employment Type: ${c.employmentType}`,
    `Probation Period: ${c.probationPeriod}`,
    `Annual CTC: ₹${c.salary} per annum`,
    `Working Hours: ${c.workingHours}`,
    `Working Days: ${c.workingDays}`,
    "",
    "1. Compensation",
    "A detailed Salary Annexure, setting out the components of your compensation, will be provided as part of your appointment documentation.",
    "Any variable compensation, incentives, bonuses or performance-linked payments, where applicable, will be subject to the Company's policies and the applicable eligibility and performance criteria.",
    "",
    "2. Probation",
    `Your employment will be subject to an initial probationary period of ${c.probationPeriodText} from your date of joining.`,
    "During this period, your performance, conduct, attendance, suitability for the role and adherence to Company policies will be evaluated. The Company may confirm your employment upon satisfactory completion of probation, subject to its applicable policies and procedures.",
    "",
    "3. Place of Work",
    "Your initial place of posting will be:",
    OFFICE_ADDRESS,
    "Depending on business requirements, you may be required to work from another Company location or undertake work-related travel, where reasonably required for the performance of your duties.",
    "",
    "4. Working Hours and Attendance",
    "You will be expected to adhere to the Company's prescribed working hours, attendance requirements, leave procedures and other applicable employment policies.",
    "Your role may require you to work additional hours or shifts from time to time based on business requirements, subject to applicable Company policies and law.",
    "",
    "5. Duties and Responsibilities",
    "You will be responsible for performing the duties associated with your position and any other reasonable responsibilities assigned to you by your reporting manager or the Company from time to time.",
    "You are expected to maintain high standards of professionalism, integrity, confidentiality, discipline and conduct while representing the Company.",
    "",
    "6. Confidentiality and Company Information",
    "During your employment, you may have access to confidential, proprietary and commercially sensitive information relating to the Company, its employees, clients, customers, partners and business operations.",
    "You will be required to maintain strict confidentiality regarding such information and comply with all applicable Company policies relating to confidentiality, information security, data protection and use of Company systems and resources.",
    "You must not disclose, copy, misuse or share confidential Company information with any unauthorised person during or after your employment, except where required by law or authorised by the Company.",
    "",
    "7. Background and Document Verification",
    "This offer is subject to satisfactory verification of the information and documents provided by you during the recruitment process.",
    "The Company reserves the right to withdraw this offer or take appropriate action in accordance with applicable law and Company policy if any information or documentation provided by you is found to be materially false, misleading, incomplete or inaccurate.",
    "",
    "8. Documents Required at the Time of Joining",
    "Please bring self-attested copies of the following documents on your date of joining, along with the originals for verification:",
    "• PAN Card",
    "• Aadhaar Card",
    `• Passport-size photographs - ${c.photoCount}`,
    "• Educational certificates and relevant mark sheets",
    "• Experience letters / relieving letters from previous employers, where applicable",
    "• Latest employment / appointment letter, where applicable",
    "• Last three months' salary slips, where applicable",
    "• Current residential address proof, if different from the address mentioned on your Aadhaar Card",
    "• Cancelled cheque or bank account / passbook copy",
    "• Previous employment reference details, where requested",
    "• Any other documents specifically requested by the HR Department",
    "Please note: Original documents may be requested solely for verification and will be returned to you after verification.",
    "",
    "9. Company Policies",
    "Your employment will be governed by the Company's policies, rules and procedures as amended from time to time.",
    "You will be expected to familiarise yourself with and comply with all applicable policies, including those relating to attendance, leave, performance, conduct, confidentiality, information security, data protection and use of Company property and systems.",
    "",
    "10. Appointment Letter",
    "This offer letter confirms the Company's intention to employ you on the terms stated above. A detailed Appointment Letter, including the complete terms and conditions of employment and applicable Salary Annexure, will be issued following completion of the required joining and verification formalities.",
    "In the event of any inconsistency between this Offer Letter and the subsequent Appointment Letter, the terms of the Appointment Letter shall prevail from the date of its execution, subject to applicable law.",
    "",
    "11. Acceptance of Offer",
    `We request you to confirm your acceptance of this offer by ${acceptBy} by signing and returning a copy of this letter to the HR Department or by providing written confirmation through the designated communication channel.`,
    `This offer will remain valid until ${validUntil}. If we do not receive your acceptance by this date, the offer may be considered withdrawn unless an extension has been agreed in writing by the Company.`,
    "",
    "We are delighted at the prospect of you joining Par Marketing Pvt. Ltd. and wish you every success in your new role.",
    "",
    "We look forward to welcoming you to the team.",
    "",
    "Yours sincerely,",
    c.companyName,
    c.signatoryName,
    c.signatoryDesignation,
    "Human Resources",
    c.companyName,
  ];
}

export { OFFICE_ADDRESS };
