/**
 * Payroll column titles (keep in sync with frontend/src/constants/salaryColumnLabels.ts).
 */
export const SALARY_COLUMN_LABELS: Record<string, string> = {
  fileList: "File list",
  employeeCode: "Emp Code",
  employeeName: "Emp Name",
  doj: "DOJ",
  process: "Process",
  department: "Department",
  gender: "Gender",
  status: "Status",
  inHand: "In Hand",
  pfEmployee: "PFAmt",
  esiEmployee: "ESIAmt",
  ptBase: "PT",
  pt: "PT",
  gratuityBase: "Gratuity",
  gratuity: "Gratuity",
  employerPf: "Employer PF",
  employerPfArr: "Employer PFARR",
  employerEsi: "Employer ESI",
  grossCtc: "Gross CTC",
  perDay: "Per Day",
  payDays: "Pay days",
  wfhDays: "WFH count",
  lateMarkCount: "Late mark count",
  grossPay: "Gross Pay",
  pfEmployeeCalc: "PF Employee",
  pfEmployer: "PF Employer",
  esicEmployer: "ESIC Employer",
  esicEmployee: "ESIC Employee",
  otherEarning: "Other Earning",
  wfhDeduction: "WFH",
  lateMarkDeduction: "Late Mark",
  incrementPercent: "Inc. %",
  increment: "Increment",
  netPay: "Netpay",
};

export const SALARY_FULL_COLUMN_KEYS = [
  "employeeCode",
  "employeeName",
  "doj",
  "process",
  "department",
  "gender",
  "status",
  "inHand",
  "pfEmployee",
  "esiEmployee",
  "ptBase",
  "gratuityBase",
  "employerPf",
  "employerPfArr",
  "employerEsi",
  "grossCtc",
  "perDay",
  "payDays",
  "grossPay",
  "gratuity",
  "pt",
  "pfEmployeeCalc",
  "pfEmployer",
  "esicEmployer",
  "esicEmployee",
  "otherEarning",
  "wfhDeduction",
  "lateMarkDeduction",
  "increment",
  "netPay",
] as const;
